version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: webhook-app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    command: node dist/main.js

volumes:
  redis_data: