name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        run: |
          echo "DATABASE_URL=postgres://postgres:postgres@postgres:5432/webhook" >> .env
          echo "REDIS_HOST=redis" >> .env

      - name: Run full app (Docker Compose)
        run: docker compose up -d --build

      - name: Wait for services
        run: sleep 15

      - name: Check running containers
        run: docker ps

      - name: Show logs (debug)
        if: failure()
        run: docker compose logs
